### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lkp520** [mcolom/full_spectrum_IASI-NG_denoising#1]
Thank you for writing such an excellent and convenient code！When I run the code full_spectrum_IASI-NG.py, I meet some errors:

FileNotFoundError: [Errno 2] No such file or directory: b'../granuleNone.nc'
FileNotFoundError: [Errno 2] No such file or directory: '../gi_precomp/decoded_granuleNone.npy'

The code are:
filename = "../gi_precomp/decoded_granule{}.npy".format(granule_num)  
filename_nc = '../granule{}.nc'.format(granule_num)

Looking forward to your answers!

**Comment by mcolom** [comment]
Thanks for your comments!
I've added code to spatially decode IASI-NG data in the code. The IASI-NG data needs to be spatially decoded, so first the daset is read and then saved as a numpy array, with the proper spatial arrangement.

If you look at the code, it does the following:
1) Check if the decoded HSI is found on disk.
2) If not, decode it spatially and save it in gi_precomp/decoded_granule{}.npy (where {} is the number of HSI). If it exists, it simple reads the decoded data it previously saved.

**Comment by lkp520** [comment]
Thank you so much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mcolom/full_spectrum_IASI-NG_denoising"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月7日(星期三) 下午3:45
收件人:&nbsp;"mcolom/full_spectrum_IASI-NG_denoising"<full_spectrum_IASI-NG_denoising@noreply.github.com&gt;;
抄送:&nbsp;"LKP"<819549620@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mcolom/full_spectrum_IASI-NG_denoising] FileNotFoundError (#1)





 
Thanks for your comments!
 I've added code to spatially decode IASI-NG data in the code. The IASI-NG data needs to be spatially decoded, so first the daset is read and then saved as a numpy array, with the proper spatial arrangement.
 
If you look at the code, it does the following:
  
Check if the decoded HSI is found on disk.
 
If not, decode it spatially and save it in gi_precomp/decoded_granule{}.npy (where {} is the number of HSI). If it exists, it simple reads the decoded data it previously saved.
